# Configuration
To be introduced on day #2

This is an aspect of Nextflow that can be confusing. There are multiple ways of loading configuration and parameters into a Nextflow. This gives us two complications:

- At which location should I be loading a configuration value?
- Given a particular parameter, how do I know where it was set?

## Precedence

1. Parameters specified on the command line (--something value)
2. Parameters provided using the -params-file option
3. Config file specified using the -c my_config option
4. The config file named nextflow.config in the current directory
5. The config file named nextflow.config in the workflow project directory
6. The config file $HOME/.nextflow/config
7. Values defined within the pipeline script itself (e.g. main.nf)

<!-- A fulsome tour of the places in which configuration can be loaded - how overwriting works, and pointing out the common footguns when setting configuration objects in profiles. Here is also an ideal time to point out the potential mistakes that can occur when profiles share the same name as Nextflow configuration blocks.
Include -params-file 
Talk about the “Danger” block	 - how to avoid the profiles footgun.

Configuration priority and precedence
Process selectors and labels
Fully qualified selector aliases

Make a note of how loading profiles drops you back to the top-level configuration block. -->
